name: publish_articles

on:
    schedule:
        # Runs every 4 hours
        - cron: "0 */4 * * *"

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Set up python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Add new articles & publish to telegram channel
              env:
                  CHANNEL: ${{ secrets.CHANNEL }}
                  BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
                  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
                  NEWS_URL_BM: ${{ secrets.NEWS_URL_BM }}
                  NEWS_URL_ML: ${{ secrets.NEWS_URL_ML }}
                  ORIGIN: ${{ secrets.ORIGIN }}
                  REFERER: ${{ secrets.REFERER }}
                  API_URL: ${{ secrets.API_URL }}
                  PDF_URL: ${{ secrets.PDF_URL }}
              run: |
                  python news.py

            - name: Commit only if new articles have been added
              run: |
                  git config --global user.email "stonksbot@example.com"
                  git config --global user.name "stonksbot"
                  git diff --quiet || (git add nepstonks.db && git commit -m "📰 db: add new articles")
                  git push origin HEAD:main
